### ISSUE TITLE
Debit and Credit creation should be idempotent

### ISSUE THREAD

**Issue by phutchins** [Storj/billing#49]
If the process for creating debits, credits and referral credits is run twice, duplicate entries should not be created. Existing entries should be updated with the data in the current run and new entries should be added.

This should all be done in such a way that there will never be a case that an entry has changed or removed such that it cannot be found and is added causing a miscalculation in balance.

**Comment by bryanchriswhite** [comment]
@phutchins I think this is fixed by that latest round of debit-generation script business we did.
