### ISSUE TITLE
Incorrect storage and bandwidth values 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/billing#59]
@dylanlott , @pgerbes1 , @bryanchriswhite .

**Normal conditions**:

- I upload 200GB/day
- "GB of storage used" increases every day as i constantly upload more data and don't delete any.
-  "Current usage" increases every day as i have to pay daily for my uploaded data.
- "Storage" in "Usage This Month" increases every day.
- "Bandwidth stays close to zero as i don't download anything, and what i download doesn't complete successfully due to the known bridge stability issues.

**Observations**:

- Current usage stopped increasing.
- "Bandwidth" in "Usage this Month" increased exponentially without any actual downloading taking place from my account.
- "Description" in "Billing History" dropped to "<0.01 GB of storage used", while i (1) Did not delete any data and (2) I am still uploading every single day.

**screenshots**

![billing issue_2](https://cloud.githubusercontent.com/assets/11735738/25333100/eda7e8f8-28e0-11e7-84ba-7f11434c6a89.png)
![billing issue](https://cloud.githubusercontent.com/assets/11735738/25333101/edc79c2a-28e0-11e7-86b0-591ffd36be51.png)

**Comment by MeijeSibbel** [comment]
@barbaraliau , @bryanchriswhite @pgerbes1 , i think you accidentally switched storage values to bandwidth and bandwidth values to storage in the bridge UI.

**Comment by pgerbes1** [comment]
@MeijeSibbel I'm currently looking into the billing oddities. Will update when I have more information.

**Comment by MeijeSibbel** [comment]
Issue is fixed.
