### ISSUE TITLE
Automate setting user free tier to false

### ISSUE THREAD

**Issue by braydonf** [Storj/billing#65]
Looks like with bitcoin payments (maybe also credit card) isFreeTier is not automatically set to false yet and requires manually setting it.

**Comment by barbaraliau** [comment]
Bitcoin payments are done manually, and the isFreeTier is set during that. There's a bug with the isFreeTier for credit cards though. I'll look into why it's not working anymore. It used to be intermittent but now looks like it's all the time.

**Comment by dylanlott** [comment]
I'll take a look at this today

**Comment by RichardLitt** [comment]
Closed as stale.
