### ISSUE TITLE
Clean e2e test and analysis of stripe ingetration, and credit & debit generation

### ISSUE THREAD

**Issue by bryanchriswhite** [Storj/billing#66]
Objective
===

In order to test whether the stripe queue changes are working as expected we need to test that given some storj usage (storage events, bucketentries, and bucket(s)), that debits, credits, and stripe invoice items are accurately generated for their respective user.

Testing Environment / Services
===

Currently everything is deployed to staging that is necessary for the test. These services are:
+ **Staging Billing**: billing.staging.storj.io - receiving api calls from billing-importer and from stripe
+ **Staging Bridge GUI**: app.staging.storj.io _(not required, just useful)_ - can be used to look at a users transactions and period total easily

Relevant files:
---
_(There's currently a decent amount of logging in a few of these files. I haven't yet replaced `console.log`s with `logger.debug`s yet in many places. I would recommend continuing to use a ubiquitous logger and replace `console.log`s as you find them.)_

### Billing: 
+ [lib/server/routes/credits.js](https://github.com/Storj/billing/blob/master/lib/server/routes/credits.js)
+ [lib/server/routes/debits.js](https://github.com/Storj/billing/blob/master/lib/server/routes/debits.js)

### Service-storage-models:
+ [lib/models/payment-processor-adapters/stripe.js](https://github.com/Storj/service-storage-models/blob/master/lib/models/payment-processor-adapters/stripe.js) - contains all the stripe specific logic for billing; i.e. where all (there may be some exceptions that are expected to be factored out later) API calls to stripe are made from
+ [lib/vendor/stripe.js](https://github.com/Storj/service-storage-models/blob/master/lib/vendor/stripe.js) - the most recently changed part of billing, contains the stripe api queue / proxy implementation

Methodology
===

_*indicates that this step can probably be done easiest by using the [staging bridge-gui](https://app.staging.storj.io)_
1) Create a new storj user*.
1) Add stripe payment processor to that user*.
    If you want payments to succeed in stripe test env you want to use this card number (see [stripe's docs](https://stripe.com/docs/testing#cards-responses)): `4000000000000077`
1) Create multiple days worth of usage data in the staging database.
    Documents required for proper debit generation:
    + `bucketentry`
    + `bucket`
    + `storageevent`
    + `frames` (maybe, not totally sure)
  
    Data generation:
    1) Create multiple buckets and bucket entries via the cli and/or bridge-gui (for buckets).
    1) Download each of your entries once via the cli to generate download storage events.
    1) You can now duplicate and manipulate these storage events to generate usage data for multiple days, changing the timestamp.
1) Generate debits for current billing period.  
    
    This can be done easily by `kubectl exec`ing _(I use an alias `kube` in my examples)_ into the running staging billing-importer container and executing the [bin/create-debits.js](https://github.com/Storj/billing/blob/master/bin/create-debits.js) bin with the appropriate args:

    _`kube` and `kns` are aliases I copied from @phutchins and you can find it [here](https://github.com/phutchins/dot-files/blob/master/bash_aliases#L71) as well as it's [bash completion](https://github.com/phutchins/dot-files/blob/master/bashrc#L84)_
  
    <pre>export KUBECONFIG=&lt;path to your kubeconfig.yml&gt;
   kns storj-staging
   kube exec -it $(kube get pods|grep billing-importer|cut -d' ' -f1) /bin/bash
   &nbsp;
   #--- now in billing-importer shell ---#
   &nbsp;
   bin/create-debits.js --help</pre>
    <pre>Usage: create-debits [options]
   &nbsp;
   Options:
   &nbsp;
     -h, --help           output usage information
     -V, --version        output the version number
     -b, --begin [time]   Begin Time in ISO Date format EX: 2017-03-27 - Default: Today
     -d, --days <number>  Number of days to generate debits for starting at Begin Time - Default: 1
     -R, --remove         Remove existing debits within the selected date range before generation (not yet implemented)
     -y, --yes            Automatically say yes to all prompts</pre>

1) Verify that the total of the given stripe user's pending invoice items matches the sum of the storj debit `amount`s for the corresponding user (and billing period). NOTE: Stripe has a miminum of 1 cent for invoice items, so the invoice item and debit amount sums should be the same to a cent.
    ### Example stripe customer "Pending Invoice Items" section:
    #### Pending invoice item(s) present
    <img width="889" alt="screen shot 2017-06-09 at 12 03 36 pm" src="https://user-images.githubusercontent.com/600733/26972251-46d04ef8-4d11-11e7-962a-0460822ae06e.png">
    
    #### No Pending invoice item(s) present
    <img width="891" alt="screen shot 2017-06-09 at 12 02 35 pm" src="https://user-images.githubusercontent.com/600733/26972208-12169438-4d11-11e7-9355-9d8fdfe479f9.png">
    
    #### Honestly not sure
    <img width="891" alt="screen shot 2017-06-09 at 12 03 01 pm" src="https://user-images.githubusercontent.com/600733/26972229-20fa53a4-4d11-11e7-8283-8cddf9b66e9f.png">

1) Generate an invoice to trigger stripe webhooks to test the billing credit route's credit creation:

    <img width="413" alt="screen shot 2017-06-09 at 12 03 56 pm" src="https://user-images.githubusercontent.com/600733/26972365-c842cdd0-4d11-11e7-823a-89a290ae88ff.png">

1) Verify that the storj user has a new credit with `paid_amount` equal to 0, and `invoiced_amount` equal to the cent-floor of the stripe invoice total.

    You can go to the "Events & Logs" section of the stripe UI and select the entries corresponding to the `invoice.created` event to get details on whether the webhook has been triggered yet, what the response was, and gives you the ability to re-trigger if you wish.

    After stripe's webhook(s) have triggered, you can use/refresh bridge-gui to verify the existence of a new credit and to verify the `paid_amount` but bridge-gui doesn't display the `invoiced_amount` of debits. You'll probably have to look at the database to get this info.

1) "Pay" the invoice via stripe to test the billing credit route's credit confirmation:
    
    <img width="878" alt="screen shot 2017-06-09 at 12 58 35 pm" src="https://user-images.githubusercontent.com/600733/26972771-6d1ba736-4d13-11e7-8825-5e490ace3b92.png">

    
1) Verify the storj user's new credit was updated with a `paid_amount` equal to the `invoiced_amount` (and by extension stripe's invoice total)*.

    You can again look at the "Events & Logs" section and look for the entries corresponding to the `invoice.payment_succeeded` or `invoice.payment_failed` events, the webhook request, response, etc.

    Again, after stripe's webhook(s) have triggered, you can use/refresh bridge-gui to verify the change in `paid_amount` since this is what's rendered into the "Amount" column of the transactions list/table.

**Comment by RichardLitt** [comment]
Closing as stale. Thank you.
