### ISSUE TITLE
Farmers are abusing the base payout by adding allot of nodes and by downloading from their own farmer

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/billing#69]
1. Currently farmer payouts are higher than the amount renters pay, which leads to abuse by users actively downloading from themselves.
2. Farmers are still abusing the base payout by running allot of nodes.

**Comment by MeijeSibbel** [comment]
This issue has causes allot of farmer turmoil and complaints because its totally unfair that a few nodes get most of the total payout amount.

**Comment by RichardLitt** [comment]
See #67. :)
