### ISSUE TITLE
Idea: Minimum billed storage period

### ISSUE THREAD

**Issue by braydonf** [Storj/billing#72]
Have a minimum billed storage length for the case that files are uploaded and immediately deleted: https://github.com/Storj/dev-meetings/blob/master/2017-8-9-summary.md#users-flooding-network-with-data-and-deleting-it

**Comment by dylanlott** [comment]
My ideas on creating a reactive billing system will fix this. I've already written the library to make it possible, just need to implement it in billing and make sure it's got a solid test suite.

**Comment by RichardLitt** [comment]
Stale.
