### ISSUE TITLE
Give people paying with STORJ tokens for storage a discount (incentivize the use of the STORJ token within the ecosystem).

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/billing#74]
Giving users that pay with the STORJ token a discount (e.g. 10-20%) will incentivize people to use and or hold the STORJ tokens, this would settle the debate about what advantage of using the STORJ token has over just using fiat. The main complaint users have (mainly token buyers) is that the STORJ token can't really be used for anything within the STORJ ecosystem and thus should have no intrinsic value or use.

**Comment by RichardLitt** [comment]
See #67.
