### ISSUE TITLE
create a "S3 Standard – Infrequent Access" competition plan 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/billing#77]
Currently S3 - infrequent access is cheaper on amazon than the Storj price, which can lead to potential customers choosing S3 over Storj. There are many farmers that want to store allot of data, but don't like Storj using up allot of bandwidth. For those farmers storing infrequent access data would be a solution.

 S3 infrequent access costs: $0.0125 / GB

**Comment by RichardLitt** [comment]
See #67.
