### ISSUE TITLE
Data storage and transfer payment scale depending on the storage amount and/or traffic generated 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/billing#78]
Most cloud storage providers offer lower prices the more the customers stores or the more they download the data. If we take S3 as a example the price of storing over 500TB of data is $0.021 / GB, then $0.050 per GB for transferring data outside of S3 for over 350TB, this means that S3 is the same price as Storj at this point, except for a minor difference in storage costs. These price differences are not good enough for such a large customer to consider Storj as a viable option, the prices have to be lower.

Creating a similar scale as in https://blog.cloudability.com/aws-s3-understanding-cloud-storage-costs-to-save/ should work.

**Comment by RichardLitt** [comment]
See #67.
