### ISSUE TITLE
Remove the 3GB/h, 10GB/day limit, just 25GB. Users can fill the 25GB right away

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/billing#83]
These rate limits are a huge pain for everyone and don't bring any advantages, only disadvantages, like loosing potential customers.

**Comment by braydonf** [comment]
This isn't the right place for this, and the advantages are around not getting denial of serviced. The settings themselves can be adjusted.

**Comment by MeijeSibbel** [comment]
Then what is the right place to open a issue for this if i may ask?, so that i can open a issue there. The advantages you mentioned don't apply also for your customers, the people that you are trying to satisfy. For them its only causing issues.
